title: Website-Template
description: A Template Website
baseurl: "/Website-Template/" # Case Sensitive 
ogimage: "https://placehold.co/1200x630"

author:
    name: John Doe
    email: johndoe@example.com


# Build settings
markdown: kramdown
source: src

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate-v2
    - jekyll-sass-converter

pagination:
    enabled: true
    per_page: 10
    permalink: "page/:num/" # or 'page/:num/' depending on your URL style

sass:
    style: compressed
    sass_dir: _sass

collections:
  products:
    output: true
    permalink: /products/:name/
    template: product